//Authentication
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAIL = 'LOGIN_FAIL'
export const ON_AUTH_INPUT_CHANGE = 'ON_AUTH_INPUT_CHANGE'

export const FORGOT_PASSWORD_REQUEST = 'FORGOT_PASSWORD_REQUEST'
export const FORGOT_PASSWORD_SUCCESS = 'FORGOT_PASSWORD_SUCCESS'
export const FORGOT_PASSWORD_FAIL = 'FORGOT_PASSWORD_FAIL'

export const REGISTER_SUCCESS = 'REGISTER_SUCCESS'
export const REGISTER_FAIL = 'REGISTER_FAIL'

export const FACEBOOK_SUCCESS = 'FACEBOOK_SUCCESS'
export const FACEBOOK_FAIL = 'FACEBOOK_FAIL'

export const EDIT_PROFILE_REQUEST = 'EDIT_PROFILE_REQUEST'
export const EDIT_PROFILE_SUCCESS = 'EDIT_PROFILE_SUCCESS'
export const EDIT_PROFILE_FAIL = 'EDIT_PROFILE_FAIL'

export const RESEND_CONFIRMATION_REQUEST = 'RESEND_CONFIRMATION_REQUEST'
export const RESEND_CONFIRMATION_SUCCESS = 'RESEND_CONFIRMATION_SUCCESS'
export const RESEND_CONFIRMATION_FAIL = 'RESEND_CONFIRMATION_FAIL'

export const ON_REGISTER_INPUT_CHANGE = 'ON_REGISTER_INPUT_CHANGE'
export const ON_EDIT_INPUT_CHANGE = 'ON_EDIT_INPUT_CHANGE'

export const CREATE_PASSWORD_REQUEST = 'CREATE_PASSWORD_REQUEST'
export const CREATE_PASSWORD_SUCCESS = 'CREATE_PASSWORD_SUCCESS'
export const CREATE_PASSWORD_FAIL = 'CREATE_PASSWORD_FAIL'

export const LOG_OUT = 'LOG_OUT'

//Venues
export const GET_VENUE_SUCCESS = 'GET_VENUE_SUCCESS'
export const GET_SPORT_NAMES_SUCCESS = 'GET_SPORT_NAMES_SUCCESS'
export const SET_ACTIVE_SPORT = 'SET_ACTIVE_SPORT'
export const TOGGLE_NEW_SPORT_SELECTION = 'TOGGLE_NEW_SPORT_SELECTION'

//OTHER
//Language selection
export const TOGGLE_MENU  = 'TOGGLE_MENU'
